### ISSUE TITLE
scala.MatchError when derive functor

### ISSUE THREAD

**Issue by chenharryhua** [typelevel/kittens#108]
the following code is successfully compiled but fail at runtime( throw MatchError exception)
```sh
sealed trait Gadt[A]
final case class Start[A](a: A) extends Gadt[A]
final case class End(a: Int, b: Int) extends Gadt[Int]

class DeriveFunctorTest extends FunSuite {
  import cats.implicits._
  val functor = cats.derived.semi.functor[Gadt]
  test("map test") {
    functor.map(End(1, 10))(_ + 1)
  }
}
```

by the way, no GADT encoding works fine:
```sh
sealed trait Adt[A]
final case class Start[A](a: A) extends Adt[A]
final case class End[A](a: Int, b: Int => A) extends Adt[A]
val functor = cats.derived.semi.functor[Adt]
 functor.map(End(1, _ + 1))(_ + 1)
```

**Comment by milessabin** [comment]
This is mainly a bug in shapeless's `Generic1` ... it's not including `End` in the representation coproduct for `Gadt`.

That aside, I don't think this is quite the right approach here. To all intents and purposes, you're attempting to define a _restricted_ functor ... there are additional constraints on the `End` branch of the GADT which can't be generically satisfied by `Functor[Gadt]`.

So I think your non-GADT encoding is the right way to go, both theoretically and because it avoids the bug.

**Comment by chenharryhua** [comment]
Thanks, Miles. Haskell defined a few rules to derive functor: https://ghc.haskell.org/trac/ghc/wiki/Commentary/Compiler/DeriveFunctor . I paste here for easy access:
```sh
  - Do nothing to an argument whose type doesn't mention 'a'
  - Apply 'f' to an argument of type 'a'
  - Apply 'fmap f' to other arguments
```
does kittens have similar rules? if yes, where can I find them?

**Comment by milessabin** [comment]
Kittens has similar rules ... you'll see instances for `F[A]` and `Const[T]#λ`.

You might think that the const rule would handle the GADT branch for `End`, but unfortunately it doesn't. The problem is that mapping with, eg., an `Int => String` must always turn a `Gadt[Int]` into a Gadt[String]` and that can't be done without changing which branch of the GADT you're on. There's no straightforward way of doing this. Are you absolutely sure that GHC handles this case?

You can of course define your own instance by hand.

**Comment by chenharryhua** [comment]
Yes, I don't think I can implement fmap by hand without cheating:
```sh
 def map[A,B](fa: Gadt[A])(f: A=>B):Gadt[B] = fa match {
   case Start(a) => Start(f(a))
   case End(a,b) => End(a,b).asInstanceOf[Gadt[B]] //cheating
}
```
Thanks Miles again. appreciate your help.

**Comment by milessabin** [comment]
A functor for `Gadt` is allowed to change the branch, so you could do something like this,
```scala
def map[A,B](fa: Gadt[A])(f: A => B): Gadt[B] = fa match {
   case Start(a) => Start(f(a))
   case End(a,b) => Start(f(a))
}
```
It's not quite cheating, but then it's most likely not what you want anyway.

**Comment by chenharryhua** [comment]
I am not sure whether the map method in the code can be compiled ? : 
```
object miles{
  sealed trait Gadt[A]
  final case class Start[A](a: A) extends Gadt[A]
  final case class End(a: Int) extends Gadt[String]
  val f = new Functor[Gadt] {
    def map[A,B](fa: Gadt[A])(f: A=>B): Gadt[B] = fa match {
      case Start(a) => Start(f(a))
      case End(a) => Start(f(a)) // type mismatch: found : int required A
    }
  }
}```

**Comment by joroKr21** [comment]
The conclusion from the discussion is that there is no mechanical way to define a `Functor` instances for the GADT example.

Which means that the derivation failing is a feature. In cases like this, one should think about the semantics of the instance, define it manually and test the laws.
