### ISSUE TITLE
[Scala 2] sequenceGeneric should handle variance

### ISSUE THREAD

**Issue by nigredo-tori** [typelevel/kittens#422]
Consider this [example](https://scastie.scala-lang.org/pS69myGUQDOWrGSfWp54NA):
```scala
case class Foo(a1: Int, a2: Int)

val seq = sequenceGeneric[Foo]

seq(
  a1 = 1.asRight,
  a2 = 2.asRight[String]
)
```
This fails to compile:

> could not find implicit value for parameter seq: cats.sequence.GenericSequencer[shapeless.labelled.FieldType[Symbol @@ String("a1"),Either[Nothing,Int]] :: shapeless.labelled.FieldType[Symbol @@ String("a2"),Either[String,Int]] :: shapeless.HNil,Playground.Foo]
error after rewriting to Playground.this.seq.applyDynamicNamed("apply")(scala.Tuple2("a1", 1.asRight), scala.Tuple2("a2", 2.asRight[String]))
possible cause: maybe a wrong Dynamic method signature?

I've played with a stripped down version of the `Sequencer` and `sequenceGeneric` (long story), and making it contravariant (see the code in https://github.com/typelevel/kittens/issues/423#issue-1090872598) has solved a similar issue for me. Though I can't say for sure that this would work for the full version.

**Comment by joroKr21** [comment]
I'm not sure what you mean by making it covariant - `F[_]` in `Sequencer` is a type member so it has no variance.

**Comment by nigredo-tori** [comment]
@joroKr21, I meant defining `Sequencer` as `trait Sequencer[-L <: HList]` (note the `-`).

In the example above, the reason for the compilation failure is that we cannot derive `Sequencer[Either[Nothing, Int] :: Either[String, Int] :: HNil]` because `Either[Nothing, *]` and `Either[String, Int]` are different functors, even though `Sequencer` instance for `::` requires them to be the same. But we can derive ``Sequencer[Either[String, Int] :: Either[String, Int] :: HNil]`, and with covariant `Sequencer` as described above that is enough.

 Alternatively, we should be able to handle this in the `Sequencer` instance for `::` (by relaxing the requirements on `F[_]`).

**Comment by joroKr21** [comment]
The issue is with the variance of `F[_]` and not `L`.
But we can't change the variance of `F[_]` in `Sequencer` because:
  1. It's a type member, not a type parameter
  2. It's used both as an argument (for `Parallel`) and as return type (`Out`)

Unfortunately there is nothing we can do. We are coming to the limitations of the Scala compiler. The syntax which supports calling `sequenceGeneric` with named arguments needs to know the type of the input `HList` before looking for a `Sequencer` instance and that type is inferred from the supplied arguments.
